config/routes.rb
Rails.application.routes.draw do
  resources :tx_schedule_references
  resources :tx_schedule_messages
  resources :tx_filter_schedules

  resources :tx_filters
  resources :tx_filter_details
  get 'transacction_type/dynamic', to: 'transacction_type#dynamic'
  resources :tconfigs
  get 'filtering_categorizations/dynamic', to: 'filtering_categorizations#dynamic'
  # get 'tx_sessions/index'

  get 'transacction_type/index', to: 'transacction_type#index'
  resources :transacction_type #'transacction_type/index', to: 'transacction_type#index'
  resources :tx_sessions
  resources :filtering_categorizations
  resources :states, :path => 'testadosxalerta'
  resources :states
  resources :testadosxalerta
  resources :table_orders
  get 'alert_release/index'
  post 'users/expire', to: 'users#expire'

  get 'users/expire', to: 'users#expire'

  get 'user_priority/index'
  get 'user_priority/assignPriority'
  get 'user_priority/assignPriorityPer'
  get 'user_priority/sessionsTran'
  get 'user_priority/groupsPer'

  get 'niv_alertamiento/index'
  get 'con_gen/index'


  filter :locale

  get 'alertc/par4'
  get 'alertc/par3'
  get 'alertc/par2'
  get 'alertc/par1'
  get 'alertn/histTran'
  get 'alertn/transacciones_alerta'
  get 'home/alertaBoton'
  get 'home/pie3'
  get 'home/pie2'
  get 'home/pie1' #, to: 'home#pie1'
  get 'home/contadorSuperior' #, to: 'home#pie1'
  get 'home/totalAlerts'
  get 'home/alertaTransaccional'
  get 'home/alertaPerfiles'
  get 'home/mensajeAlerta'
  get 'home/totalPoratender'
  get 'home/totalAtendidas'
  get 'home/settings_index'

  get 'chart/empty'
  get 'chart/pies'
  get 'chart/dynamic'

  resources 'chart'


  get 'alertn/alertTran', to: 'alertn#alertTran'
  get 'tbitacora/tbitacora'
  get 'tbitaobse/tbitaobse'
  get 'alertn/alertPer', to: 'alertn#alertPer'
  get 'alertc/busqueda', to: 'alertc#busqueda'

  resources :groups

  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :alertn
  resources :alertc
  resources :con_gen
  resources :chart, only: [:index, :dynamic]
  resources :home, only: [:index, :create]
  resources :mail_groups
  resources :gestor_settings


  # get '/:locale' => 'home#index'

  # devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in'}
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :mail_groups
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html, :js

  # @@group = "Group"

  # GET /groups
  # GET /groups.json
  def index
    @id_usuario = current_user.id
    @id_aplicacion = 25
    @idTipoReg = 11 #Index
    @fecha = Time.now.strftime("%F")
    @hora = Time.now.strftime("%k:%M:%S.00000")
    @men = "Groups Index"


    @tbit = Tbitacora.new
    @tbit.IdUsuario = @id_usuario
    @tbit.IdAplicacion = @id_aplicacion
    @tbit.IdTipoReg = @idTipoReg #Index
    @tbit.Fecha = @fecha
    @tbit.Hora = @hora
    @tbit.Mensaje = @men
    @tbit.save

    # if current_user
    #   @cu = current_user.profile_id
    #   if @cu == 1
    #     @per = Permission.where("view_name = 'Group' and profile_id = ?", @cu)
    #     @per.each do |permisos|
    #       @uno = permisos.view_name
    #       @crearGroup = permisos.crear
    #       @editarGroup = permisos.editar
    #       @leerGroup = permisos.leer
    #       @eliminarGroup = permisos.eliminar
    #
    #       if permisos.view_name == @@group
    #
    #         @@crear = permisos.crear
    #         @@editar = permisos.editar
    #         @@leer = permisos.leer
    #         @@eliminar = permisos.eliminar
    #
    #         @crear = permisos.crear
    #         @editar = permisos.editar
    #         @leer = permisos.leer
    #         @eliminar = permisos.eliminar
    #       end
    #     end
    #     if ((@@leer == 2) || (@@crear == 8) || (@@editar == 4) || (@@eliminar == 1))
    @groups = Group.all
    @consulta = Referenciadealerta.select(:campo).group(:campo)



    #     else
    #       @Without_Permission = 100
    #       redirect_to home_index_path, :alert => t('all.not_access')
    #     end
    #   else
    #     @Without_Permission = 100
    #     redirect_to home_index_path, :alert => t('all.not_access')
    #   end
    # else
    #   @Without_Permission = 100
    #   redirect_to new_user_session_path, :alert => t('all.please_continue')
    # end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @id_usuario = current_user.id
    @id_aplicacion = 25
    @idTipoReg = 13 #Show
    @fecha = Time.now.strftime("%F")
    @hora = Time.now.strftime("%k:%M:%S.00000")
    @men = "Email Groups Show"

    @tbit = Tbitacora.new
    @tbit.IdUsuario = @id_usuario
    @tbit.IdAplicacion = @id_aplicacion
    @tbit.IdTipoReg = @idTipoReg #Index
    @tbit.Fecha = @fecha
    @tbit.Hora = @hora
    @tbit.Mensaje = @men
    @tbit.save
  end

  # GET /groups/new
  def new
    # if current_user
    #   @cu = current_user.profile_id
    #   if @cu == 1
    #     @per = Permission.where("view_name = 'Group' and profile_id = ?", @cu)
    #     @per.each do |permisos|
    #       @uno = permisos.view_name
    #       @crearGroup = permisos.crear
    #       if permisos.view_name == @@group
    #         @@crear = permisos.crear
    #         @crear = permisos.crear
    #       end
    #     end
    #     if ((@@crear == 8))
    @group = Group.new
    @btn = false
    @consulta = Referenciadealerta.select(:campo).group(:campo)
    #     else
    #       @Without_Permission = 100
    #       redirect_to home_index_path, :alert => t('all.not_access')
    #     end
    #   else
    #     @Without_Permission = 100
    #     redirect_to home_index_path, :alert => t('all.not_access')
    #   end
    # else
    #   @Without_Permission = 100
    #   redirect_to new_user_session_path, :alert => t('all.please_continue')
    # end
  end

  # GET /groups/1/edit
  def edit

    # if current_user
    #   @cu = current_user.profile_id
    #
    #   if @cu == 1
    #     @per = Permission.where("view_name = 'Group' and profile_id = ?", @cu)
    #     @per.each do |permisos|
    #       @uno = permisos.view_name
    #       @@editarGroup = permisos.editar
    #       if permisos.view_name == @@group
    #         @@editar = permisos.editar
    #         @editar = permisos.editar
    #       end
    #     end
    #     if ((@@editar == 4))
    @btn = true
    @consulta = Referenciadealerta.select(:campo).group(:campo)
    #     else
    #       @Without_Permission = 100
    #       redirect_to home_index_path, :alert => t('all.not_access')
    #     end
    #   else
    #     @Without_Permission = 100
    #     redirect_to home_index_path, :alert => t('all.not_access')
    #   end
    #
    # else
    #   @Without_Permission = 100
    #   redirect_to new_user_session_path, :alert => t('all.please_continue')
    # end
  end

  # POST /groups
  # POST /groups.json
  def create
    @id_usuario = current_user.id
    @id_aplicacion = 25
    @idTipoReg = 9 #Create
    @fecha = Time.now.strftime("%F")
    @hora = Time.now.strftime("%k:%M:%S.00000")
    @men = "Email Groups New"
    # alertas = cuando se entre a editar alerta se va a guardar el id de tbitacora(alerta que se está atendiendo) y el id de producto, transaccional o perfiles <== aun no


    @tbit = Tbitacora.new
    @tbit.IdUsuario = @id_usuario
    @tbit.IdAplicacion = @id_aplicacion
    @tbit.IdTipoReg = @idTipoReg
    @tbit.Fecha = @fecha
    @tbit.Hora = @hora
    @tbit.Mensaje = @men
    @tbit.save
    @group = Group.new(group_params)

    @group.detail = params[:campo1]
    @group.reference = params[:campo5]
    @group.area = params[:campo3]
    @group.hist_alert = params[:campo4]
    @group.hist_trans = params[:campo5]
    @group.fraude = params[:camporadio]

    respond_to do |format|

      if Group.where("name like ?", @group.name).exists?
        format.html {
          @error = t('notice.blackup')
          render action: :new
        }
      else
        if params[:save_group]
          if @group.save
            format.html {redirect_to groups_path, notice: t('notice.succes')}
            format.json {render :show, status: :created, location: @group}
          else
            format.html {render :new}
            format.json {render json: @group.errors, status: :unprocessable_entity}
          end
        elsif params[:save_mails]
          if @group.save
            format.html {redirect_to :controller => 'mail_groups', :action => 'new', :id => @group.id, notice: t('notice.created', resource: t('notice.group'))}
            format.json {render :show, status: :created, location: @group}
          else
            format.html {render :new}
            format.json {render json: @group.errors, status: :unprocessable_entity}
          end
        end
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    @id_usuario = current_user.id
    @id_aplicacion = 25
    @idTipoReg = 10 #Edit
    @fecha = Time.now.strftime("%F")
    @hora = Time.now.strftime("%k:%M:%S.00000")
    @men = "Email Groups Edit"

    @tbit = Tbitacora.new
    @tbit.IdUsuario = @id_usuario
    @tbit.IdAplicacion = @id_aplicacion
    @tbit.IdTipoReg = @idTipoReg #Edit
    @tbit.Fecha = @fecha
    @tbit.Hora = @hora
    @tbit.Mensaje = @men
    @tbit.save
    @per = Profile.where("id = ?", params[:id])

    @group.detail = params[:campo1]
    @group.reference = params[:campo5]
    @group.area = params[:campo3]
    @group.hist_alert = params[:campo4]
    @group.hist_trans = params[:campo5]
    @group.fraude = params[:camporadio]

    respond_to do |format|
      if params[:save_group]
        if @group.update(group_params)
          format.html {redirect_to groups_path, notice: t('notice.update')}
          format.json {render :show, status: :ok, location: @group}
        else
          format.html {render :edit}
          format.json {render json: @group.errors, status: :unprocessable_entity}
        end
      elsif params[:save_mails]
        if @group.update(group_params)
          format.html {redirect_to :controller => 'mail_groups', :action => 'new', :id => @group.id, notice: t('notice.created', resource: t('notice.group'))}
          format.json {render :show, status: :created, location: @group}
        else
          format.html {render :new}
          format.json {render json: @group.errors, status: :unprocessable_entity}
        end
      end
    end
  end


  def destroy
    # if current_user
    #   @cu = current_user.profile_id
    #   if @cu == 1
    #     @per = Permission.where("view_name = 'Group' and profile_id = ?", @cu)
    #     @per.each do |permisos|
    #       @uno = permisos.view_name
    #       @@eliminarGroup = permisos.eliminar
    #       if permisos.view_name == @@group
    #         @@eliminar = permisos.eliminar
    #         @eliminar = permisos.eliminar
    #       end
    #     end
    #     if ((@@eliminar == 1))
    @id_usuario = current_user.id
    @id_aplicacion = 25
    @idTipoReg = 12 #Index
    @fecha = Time.now.strftime("%F")
    @hora = Time.now.strftime("%k:%M:%S.00000")


    @tbit = Tbitacora.new
    @tbit.IdUsuario = @id_usuario
    @tbit.IdAplicacion = @id_aplicacion
    @tbit.IdTipoReg = @idTipoReg #Index
    @tbit.Fecha = @fecha
    @tbit.Hora = @hora

    @mails = MailGroup.where("group_id = ?", @group.id);
    @mails.each do |mail|
      mail.destroy
    end

    @tbit.Mensaje = @group.to_json
    @tbit.save

    @group.destroy
    respond_to do |format|
      format.js
      format.html {redirect_to post_url, notice: t('notice.destroy')}
      format.json {head :no_content}
    end
    #     else
    #       @Without_Permission = 100
    #       redirect_to home_index_path, :alert => t('all.not_access')
    #     end
    #
    #   else
    #     @Without_Permission = 100
    #     redirect_to home_index_path, :alert => t('all.not_access')
    #   end
    #
    # else
    #   @Without_Permission = 100
    #   redirect_to new_user_session_path, :alert => t('all.please_continue')
    # end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group.html.erb
<tr id="dato_<%= group.id %>">
  <td class="text-center"><%= group.name %></td>
  <td align="center" data-toggle="tooltip" data-placement="bottom" title=<%= t('all.add') %> align="center">
    <% if group.mail_groups.count > 0 %>
      <%= group.mail_groups.count %> |
      <%= link_to ('<button class="btn btn-primary btn-xs" type="button"><i class="fa fa-plus"></i></button>').html_safe, new_mail_group_path(:id_group => group.id) %>
    <% else %>
      <%= t('views.groups_index.vacio') %>
      <%= link_to ('<button class="btn btn-primary btn-xs" type="button"><i class="fa fa-plus"></i></button>').html_safe, new_mail_group_path(:id_group => group.id) %>
    <% end %>
  </td>
  <td align="center" data-toggle="tooltip" data-placement="bottom" title=<%= t('all.show') %> align="center">
    <%#= if @leerEmail == 2 %>
    <%= link_to '<button class="btn btn-primary btn-xs" type="button"><i class="fa fa-file-text "></i></button>'.html_safe, {:controller => "mail_groups", :action => "index", :id => group.id}, :data => {:no_turbolink => true} %>
    <%# end %>
  </td>
  <td align="center" data-toggle="tooltip" data-placement="bottom" title=<%= t('all.edit') %> align="center">
    <%# if @editarEmail == 4 %>
    <%= link_to '<button class="btn btn-warning btn-xs" type="button"><i class="fa fa-pencil"></i></button>'.html_safe, edit_group_path(group) %>
    <%# end %>
  </td>
  <td align="center" data-toggle="tooltip" data-placement="bottom" title=<%= t('all.destroy') %> align="center">
    <%# if @eliminarEmail == 1 %>
    <button class="btn btn-danger btn-xs  eliminar" type="button" id="<%= group.id %>">
      <i class="fa fa-trash-o"></i>
    </button>
    <%# end %>
  </td>
</tr>

app/views/groups/destroy.js.erb
$('#dato_<%= @group.id %>').fadeOut();

app/views/groups/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.groups_edit.title') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">
        <%= render 'form', group: @group %>
      </div>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="block-area" id="responsiveTable">
  <div class="ibox-title">
    <h1><%= t('all.mail_Groups') %></h1>
    <div class="panel">
      <div class="panel-body">
        <div class="block-area" id="tableBordered">
          <div class="ibox-content">

            <%#= if @crearEmail == 8 %>
            <%= link_to '<i class="fa fa-envelope"></i> '.html_safe + t('views.groups_index.newBtn'), {:controller => "groups", :action => "new", :profile_id => current_user.profile_id}, class: 'btn btn-primary btn-xs' %>
            <%# end %>
            <div class="table footable">
              <table class="table table-bordered table-striped table-condensed toggle-circle-filled title" datapagesize="8" data-filter=#filter id="table">
                <br>
                <thead>
                <tr>
                  <th class="text-center"><%= t('views.groups_index.name') %></th>
                  <th class="text-center"><%= t('views.groups_index.correos') %></th>
                  <th class="text-center"><%= t('all.show') %></th>
                  <th class="text-center" data-hide="phone"><%= t('all.edit') %> </th>
                  <th class="text-center" data-hide="phone"><%= t('all.destroy') %></th>
                </tr>
                </thead>

                <tbody id="team">
                <%= render @groups %>
                </tbody>
                <tfoot>
                <tr>
                  <td colspan="7">
                    <ul class="pagination pull-right"></ul>
                  </td>
                </tr>
                </tfoot>
              </table>
            </div>
            <%#= if @crearEmail == 8 %>
            <%= link_to '<i class="fa fa-envelope"></i> '.html_safe + t('views.groups_index.newBtn'), {:controller => "groups", :action => "new", :profile_id => current_user.profile_id}, class: 'btn btn-primary btn-xs' %>
            <%# end %>
            <br>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" language="javascript" class="init">

    $(document).on("click", ".eliminar", function () {
        var id = this.id;
        swal({
                title: '<%= t('views.mess_view_title')%>',
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "<%= t('views.mess_view_swall_confirm')%> ",
                cancelButtonText: "<%= t('views.mess_view_swall_cancel')%>",
                closeOnConfirm: false,
                closeOnCancel: false
            },
            function (isConfirm) {
                if (isConfirm) {
                    swal({
                            title: '<%= t('views.mess_view_title2')%>',
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "<%= t('views.mess_view_swall_confirm')%> ",
                            cancelButtonText: "<%= t('views.mess_view_swall_cancel')%>",
                            closeOnConfirm: false,
                            closeOnCancel: false
                        },
                        function (isConfirm) {
                            if (isConfirm) {
                                $.ajax({
                                    type: "POST",
                                    beforeSend: function (xhr) {
                                        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
                                    },
                                    url: "/groups/" + id,
                                    data: {"_method": "delete"},
                                })
                                //swal("<%= t('views.mess_view_swall')%>");
                                swal(
                                    {
                                        title: '<%= t('views.mess_view_swall')%>',
                                        type: "success",
                                        confirmButtonText: "OK",
                                    })
                            } else {
                                swal("<%= t('views.mess_view_swall_cancel_1')%>");
                            }
                        })
                } else {
                    swal("<%= t('views.mess_view_swall_cancel_1')%>");
                }
            });
    })
</script>

app/views/groups/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.groups_new.title') %></h1>
      </div>
      <div class="ibox-content" id="responsiveTable">
        <%= render 'form', group: @group %>
      </div>
    </div>
  </div>
</div>