config/routes.rb
Rails.application.routes.draw do
  resources :tx_schedule_references
  resources :tx_schedule_messages
  resources :tx_filter_schedules

  resources :tx_filters
  resources :tx_filter_details
  get 'transacction_type/dynamic', to: 'transacction_type#dynamic'
  resources :tconfigs
  get 'filtering_categorizations/dynamic', to: 'filtering_categorizations#dynamic'
  # get 'tx_sessions/index'

  get 'transacction_type/index', to: 'transacction_type#index'
  resources :transacction_type #'transacction_type/index', to: 'transacction_type#index'
  resources :tx_sessions
  resources :filtering_categorizations
  resources :states, :path => 'testadosxalerta'
  resources :states
  resources :testadosxalerta
  resources :table_orders
  get 'alert_release/index'
  post 'users/expire', to: 'users#expire'

  get 'users/expire', to: 'users#expire'

  get 'user_priority/index'
  get 'user_priority/assignPriority'
  get 'user_priority/assignPriorityPer'
  get 'user_priority/sessionsTran'
  get 'user_priority/groupsPer'

  get 'niv_alertamiento/index'
  get 'con_gen/index'


  filter :locale

  get 'alertc/par4'
  get 'alertc/par3'
  get 'alertc/par2'
  get 'alertc/par1'
  get 'alertn/histTran'
  get 'alertn/transacciones_alerta'
  get 'home/alertaBoton'
  get 'home/pie3'
  get 'home/pie2'
  get 'home/pie1' #, to: 'home#pie1'
  get 'home/contadorSuperior' #, to: 'home#pie1'
  get 'home/totalAlerts'
  get 'home/alertaTransaccional'
  get 'home/alertaPerfiles'
  get 'home/mensajeAlerta'
  get 'home/totalPoratender'
  get 'home/totalAtendidas'
  get 'home/settings_index'

  get 'chart/empty'
  get 'chart/pies'
  get 'chart/dynamic'

  resources 'chart'


  get 'alertn/alertTran', to: 'alertn#alertTran'
  get 'tbitacora/tbitacora'
  get 'tbitaobse/tbitaobse'
  get 'alertn/alertPer', to: 'alertn#alertPer'
  get 'alertc/busqueda', to: 'alertc#busqueda'

  resources :groups

  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :alertn
  resources :alertc
  resources :con_gen
  resources :chart, only: [:index, :dynamic]
  resources :home, only: [:index, :create]
  resources :mail_groups
  resources :gestor_settings


  # get '/:locale' => 'home#index'

  # devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in'}
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/tx_sessions.rb
class TxSessions < ApplicationRecord
  # has_many :tx_filters, :pri ,:dependent => :destroy
  has_many :tx_filters, :foreign_key => "Session_id", :dependent => :destroy
  has_many :tx_schedule_references, :foreign_key => "session_id", :dependent => :destroy

end

app/controllers/tx_sessions_controller.rb
class TxSessionsController < ApplicationController
  before_action :set_tx_session, only: [:show, :edit, :update, :destroy]

  # GET /tx_sessions
  # GET /tx_sessions.json

  @@session_name = "Sessions"

  def index

    if current_user
      @cu = current_user.profile_id

      if @cu != 0
        # @permisos = Permission.where("view_name = 'Sessions' and profile_id = ?", @cu)
        #
        # @permisos.each do |permisos|
        #   @crearSession = permisos.crear
        #   @editarSession = permisos.editar
        #   @leerSession = permisos.leer
        #   @eliminarSession = permisos.eliminar
        #
        #   if permisos.view_name == @@session_name
        #     @@crearSession = permisos.crear # 8
        #     @@editarSession = permisos.editar # 4
        #     @@leerSession = permisos.leer # 2
        #     @@eliminarSession = permisos.eliminar # 1
        #
        #     @crearSession = permisos.crear
        #     @editarSession = permisos.editar
        #     @leerSession = permisos.leer
        #     @eliminarSession = permisos.eliminar
        #
        #
        #   end
        #
        # end

        if current_user.habilitado == 0
          # if ( @@crearSession == 8 || @@editarSession == 4 || @@leerSession == 2 || @@eliminarSession == 1 )
            ##Aquí va el código que leera el index
            #
            # @tx_sessions = TxSessions.all
            tx_sessions = TxSessions.all
            gon.sesiones = tx_sessions

            # Gon para Description
            desFiltro = TxFilters.all
            gon.desFiltros = desFiltro

            ## Gon para llenar selects Layout, Formato de ventana modal
            tFormatos = Tformatos.all
            gon.formatos = tFormatos

            tCampos = Tcamposformato.all
            gon.tCamposFormatos = tCampos

            tLays = Tcamposlay.all
            gon.tCamposLays = tLays
            gon.false = true


            # Paginado de kaminari
            @tx_sessions = TxSessions.order("Id").page(params[:page]).per(10)

          # else
          #   @Without_Permission = 100
          #   redirect_to home_index_path, :alert => t('all.not_access')
          # end
        else
          @Without_Permission = 100
          redirect_to home_index_path, :alert => t('all.not_enabled')
        end
      else
        @Without_Permission = 100
        redirect_to new_user_session_path, :alert => t('all.please_continue')
      end
    else
      @Without_Permission = 100
      redirect_to new_user_session_path, :alert => t('all.please_continue')
    end
  end

  # GET /tx_sessions/1
  # GET /tx_sessions/1.json
  def show
  end

  # GET /tx_sessions/new
  def new
    if current_user
      @cu = current_user.profile_id

      if @cu != 0
        @permisos = Permission.where("view_name = 'Sessions' and profile_id = ?", @cu)

        @permisos.each do |permisos|
          @crearSession = permisos.crear
          @editarSession = permisos.editar
          @leerSession = permisos.leer
          @eliminarSession = permisos.eliminar

          if permisos.view_name == @@session_name
            @@crearSession = permisos.crear # 8
            @@editarSession = permisos.editar # 4
            @@leerSession = permisos.leer # 2
            @@eliminarSession = permisos.eliminar # 1

            @crearSession = permisos.crear
            @editarSession = permisos.editar
            @leerSession = permisos.leer
            @eliminarSession = permisos.eliminar


          end

        end

        if current_user.habilitado == 0
          if ( @@crearSession == 8 || @@editarSession == 4 || @@leerSession == 2 || @@eliminarSession == 1 )
            ##Aquí va el código que leera el index
            #
            #
            @tx_session = TxSessions.new
            @edt = false;

            tx_sessions = TxSessions.all
            gon.sesiones = tx_sessions

            tFormatos = Tformatos.all
            gon.formatos = tFormatos

            tCampos = Tcamposformato.all
            gon.tCamposFormatos = tCampos

            tLays = Tcamposlay.all
            gon.tCamposLays = tLays
            gon.false = true

          else
            @Without_Permission = 100
            redirect_to home_index_path, :alert => t('all.not_access')
          end
        else
          @Without_Permission = 100
          redirect_to home_index_path, :alert => t('all.not_enabled')
        end
      else
        @Without_Permission = 100
        redirect_to new_user_session_path, :alert => t('all.please_continue')
      end
    else
      @Without_Permission = 100
      redirect_to new_user_session_path, :alert => t('all.please_continue')
    end
  end

  # GET /tx_sessions/1/edit
  def edit
    if current_user
      @cu = current_user.profile_id

      if @cu != 0
        @permisos = Permission.where("view_name = 'Sessions' and profile_id = ?", @cu)

        @permisos.each do |permisos|
          @crearSession = permisos.crear
          @editarSession = permisos.editar
          @leerSession = permisos.leer
          @eliminarSession = permisos.eliminar

          if permisos.view_name == @@session_name
            @@crearSession = permisos.crear # 8
            @@editarSession = permisos.editar # 4
            @@leerSession = permisos.leer # 2
            @@eliminarSession = permisos.eliminar # 1

            @crearSession = permisos.crear
            @editarSession = permisos.editar
            @leerSession = permisos.leer
            @eliminarSession = permisos.eliminar


          end

        end

        if current_user.habilitado == 0
          if ( @@crearSession == 8 || @@editarSession == 4 || @@leerSession == 2 || @@eliminarSession == 1 )
            ##Aquí va el código que leera el index
            #
            @edt = true;
          else
            @Without_Permission = 100
            redirect_to home_index_path, :alert => t('all.not_access')
          end
        else
          @Without_Permission = 100
          redirect_to home_index_path, :alert => t('all.not_enabled')
        end
      else
        @Without_Permission = 100
        redirect_to new_user_session_path, :alert => t('all.please_continue')
      end
    else
      @Without_Permission = 100
      redirect_to new_user_session_path, :alert => t('all.please_continue')
    end
  end

  # POST /tx_sessions
  # POST /tx_sessions.json
  def create


    if (params[:_method].present? && params[:_method] == "update")
      @valorActive = params[:Inactive]
      @idSe = params[:Id]

      @tx_session = TxSessions.where(:Id => @idSe)
      @tx_session.each do |session|
        session.Inactive = @valorActive
        session.save
      end
    else
      ##### Vairables de AJAX #####
      # // Variables de la Sesión
      #
      @idLay = params[:selectLay]
      @idFormat = params[:selectFormato]

      @tx_session = TxSessions.new(tx_session_params)
      # @tx_session = TxSessions.new
      @tx_session.Lay_id = @idLay
      @tx_session.Format_id= @idFormat
      # @tx_session.Description = @desSession
      @tx_session.Inactive = 0
      @tx_session.Update = 0
      @tx_session.save

      # // Variables del Filtro
      @desFilter = params[:filter_name]
      @typeFilter = params[:type_filter]
      @background = params[:backgroundColor]

      # // Detalle del filtro
      @detalleFiltro = params[:condicionesFiltro].split(',')
      @idUser = params[:keyId]

      respond_to do |format|
        if @tx_session.save

          @tx_session_filter = TxFilters.new
          @tx_session_filter.Session_id = @tx_session.id
          @tx_session_filter.Description = @desFilter
          @tx_session_filter.Order_number = @typeFilter
          @tx_session_filter.Backgroundcolor = @background
          @tx_session_filter.save

          #// Detalle del Filtro
          @cont = 0
          @numCondi = 0
          @crearCondicion = false

          @conector
          @negado
          @operador
          @parentesis
          @valor
          @campoFormatoId
          @posision
          @length

          @detalleFiltro.each do | datoFiltro |
            @cont += 1

            if ( @cont === 1 )
              @conector = datoFiltro
            elsif ( @cont === 2 )
              @negado = datoFiltro
            elsif ( @cont === 3 )
              @operador = datoFiltro
            elsif ( @cont === 4 )
              @parentesis = datoFiltro
            elsif ( @cont === 5 )
              @valor = datoFiltro
            elsif ( @cont === 6 )
              @campoFormatoId = datoFiltro
            elsif ( @cont === 7 )
              @posision = datoFiltro
            elsif ( @cont === 8 )
              @length = datoFiltro
              @cont = 0
              @crearCondicion = true
            end

            if ( @crearCondicion  === true )
              @crearCondicion = false
              @numCondi += 1
              # @tx_filter_detail = TxFilterDetail.new(tx_filter_detail_params) marco error enviandolo desde el metodo new de session
              @tx_filter_detail = TxFilterDetail.new
              @tx_filter_detail.filter_id = @tx_session_filter.id
              @tx_filter_detail.conditionnumber = @numCondi
              @tx_filter_detail.connector = @conector
              @tx_filter_detail.denied = @negado
              @tx_filter_detail.operator = @operador
              @tx_filter_detail.parenthesis = @parentesis
              @tx_filter_detail.value = @valor
              @tx_filter_detail.fieldFormat_id = @campoFormatoId
              @tx_filter_detail.position = @posision
              @tx_filter_detail.lenght = @length
              @tx_filter_detail.key_id = @idUser
              @tx_filter_detail.save
            end
          end

          @id_Session = @tx_session.id

          ### Guardando campos de referencia
          @camposRefencia = params[:camposRef].split(',')
          @camposRefencia.each do | campoRef |
            @tx_schedules_reference = TxScheduleReference.new

app/helpers/tx_sessions_helper.rb
module TxSessionsHelper
end

app/views/tx_sessions/_row.html.erb
<tr id="<%= fil.id %>" class="treegrid-<%= @order %> treegrid-parent-<%= @parent %>">
  <td><strong class="filDes"><%= fil.Description %></strong></td>
  <td>
    <% if fil.Order_number == 0 %>
      <div class="cube-bg cube-filter-primray "></div> <span class="typeFiSpa">Principal</span>
    <% elsif fil.Order_number != 0 %>
      <div class="cube-bg cube-filter-sec "></div> <span class="typeFiSpa">Secundario</span>
    <%# else if  %>
<!--      <div class="cube-bg cube-filter-group "></div> <span class="typeFiSpa">Grupal</span>-->
    <% end %>
  </td>
  <td><input type="checkbox" class="democ" onclick="toggle(this)"></td>
  <% @tx_filter_schedules = TxFilterSchedule.where(:filter_id => fil.id).count %>
  <td>
    <% if @tx_filter_schedules > 0  %>
      <a class="btn btn-primary btn-xs"><%= @tx_filter_schedules %></a> |
    <% else  %>
      <span class="text-danger bg-danger">Sin horarios</span> |
    <% end %>
    <%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_tx_filter_schedule_path(:idFiltro => fil.id), remote: true, class:'btn btn-primary btn-xs' %>
  </td>
  <td>Referencia</td>
  <td><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_tx_filters_path(fil), remote: true, class:'btn btn-warning btn-xs' %></td>
  <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, fil, method: :delete, class:'btn btn-danger btn-xs' %></td>
</tr>

app/views/tx_sessions/edit.html.erb
<%= render 'form', tx_session: @tx_session %>

app/views/tx_sessions/index.html.erb
<%= stylesheet_link_tag "tx_sessions" %>
<!--<p id="notice"><%#= notice %></p>-->
<input id="userId" type="hidden" name="userId"value="<%= current_user.id %>">
<div class="row ">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h1><%= t('views.tx_session_index.session') %></h1>
        <div class="ibox-content">
          <% if @crearSession = 8 %>
            <%= link_to '<button class="btn btn-primary btn-xs" type="button" title="New Session"><i class="fa fa-user-circle-o"></i> '.html_safe + t('all.new') + '</button>'.html_safe, new_tx_sessions_path %>
          <% end %>
          <br/>
          <br/>

          <div class="row">
            <div class="col-lg-12 text-right">
              <div>
                <%= page_entries_info @tx_sessions, entry_name: t('views.tx_session_index.session') %>
              </div>
              <%= paginate @tx_sessions, :theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm"%>
            </div>
          </div>
          <table class="tree table text-center">
            <thead>
              <tr>
                <th class="text-center" >#</th>
                <th class="text-center" ><%= t('views.tx_session_index.description') %></th>
                <th class="text-center" >Campos Referencía</th>
                <th class="text-center" ><%= t('views.tx_session_index.filter_count') %></th>
                <th class="text-center" ><%= t('views.tx_session_index.new_sess_fil') %></th>
                <th class="text-center" ><%= t('views.tx_session_index.active') %></th>
                <th class="text-center" data-hide="phone, table" class="text-center"><%= t('all.edit') %></th>
                <th class="text-center" data-hide="phone, table" class="text-center"><%= t('all.delete') %></th>
              </tr>
            </thead>
            <tbody>
            <% @order = 0 %>
            <%# numSes = 0 %>
              <% @tx_sessions.each do |tx_session| %>
                <% @order +=1 %>
                <%# numSes +=1 %>
                <% @parent = @order %>
                <tr id="session<%= tx_session.id %>" class="treegrid-<%= @order %>">
                  <!-- Orden de la sesión -->
                  <td><%= tx_session.id %></td>
                  <!-- Descripción de la Sesión -->
                  <td class="nameSession"><%= tx_session.Description %></td>
                  <!-- Campos de Refencía -->
                  <td>
                    <% @references = tx_session.tx_schedule_references.all %>
                    <% @references.each do | cmpRef | %>
                      <%= cmpRef.field_formatId %>
                    <% end %>
                  </td>
                  <!-- Total de Filtros -->
                  <td>
                    <input type='hidden' id='sesion_<%= tx_session.Id %>' value='<%= tx_session.Inactive %>'>
                    <% cuenta = tx_session.tx_filters.count %>

                    <% if @editarSession = 4 %>
                      <% if cuenta >= 1%>
                        <% @id = tx_session.id %>
                        <% @filtro = TxFilter.order('order_number ASC').where(:Session_id => @id) %>
                        <a tabindex="0" class="btn btn-primary btn-xs" role="button" data-html="true" data-toggle="popover" data-trigger="focus" title="<b><%= t('views.tx_filter_index.title') %>s</b>" data-content="
                          <% @filtro.each do | filtro | %>
                            <% if filtro.Order_number == 0 %>
                              <%= @idDetalle %>
                              <input type='hidden' id='filtro_<%= filtro.Id %>' value='<%= tx_session.Id %>'>
                              <button class='btn btn-primary btn-xs edFil' value='<%=  filtro.Id %>'><%= filtro.Description %></button>
                              <br>
                            <% else %>
                                <%= @idDetalle %>
                                <input type='hidden' id='filtro_<%= filtro.Id %>' value='<%= tx_session.Id %>'>
                              -- <button class='btn btn-warning btn-xs edFil'  value='<%=  filtro.Id %>'><%= filtro.Description %></button> <button class='btn btn-danger btn-xs eliminarFiltro' value='<%=  filtro.Id %>' title='Eliminar Filtro'><i class='fa fa-trash-o'></i></button>
                                 <br>
                            <% end %>
                          <% end %>
                        ">
                          <%= cuenta %>
                        </a>
                      <% else %>
                        <span class="btn-warning btn-xs">0</span>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <% @Sesions = TxFilter.order('order_number ASC').where(:Session_id => @id).where(:Order_number => 0).present? %>
                    <input type="hidden" id="<%= tx_session.id %>" name="existPrincipal" value="<%= @Sesions %>">
                    <% if @crearSession = 8 %>
                      <%= link_to '<i class="fa fa-filter"></i>'.html_safe, new_tx_filters_path(:idSession => tx_session.id), remote: true,  class:'btn btn-primary btn-xs', title:'Nuevo Filtro' %>
                    <% end %>
                   </td>
                  <td>
                    <% if tx_session.Inactive == "1" %>
                      <% check = "checked" %>
                    <% else %>
                      <% check = "" %>
                    <% end %>

                    <div class="checkbox">
                      <input type="checkbox" id=<%= tx_session.Id %> class="active" value="<%= tx_session.Inactive %>" <%= check %>>
                      <label for="checkbox1">
                      </label>
                    </div>
                  </td>
                  <td>
                    <% if @editarSession = 4 %>
                    <%= link_to '<button class="btn btn-warning btn-xs " type="button"><i class="fa fa-pencil"></i></button>'.html_safe, edit_tx_sessions_path(tx_session), title:'Editar Sesión' %>
                    <% end %>
                  </td>
                  <td>
                    <% if @eliminarSession = 1 %>
                    <button class="btn btn-danger btn-xs eliminarSesion" type="button" id="<%= tx_session.Id %>" title="Eliminar Sesión" ><i class="fa fa-trash-o"></i></button>
                    <% end %>
                  </td>
                </tr>
                <!-- Crear los hijos de la Tr padre -->
                <% @tx_filter = TxFilter.where(:Session_id => tx_session.Id )  %>
                <% if @tx_filter.present? %>
                  <% @order+=1 %>
                  <tr class="treegrid-<%= @order %> treegrid-parent-<%= @parent %>" style="background-color: #003057; color: #fff;">
                    <td>Filtro</td>
                    <td>Tipo</td>
                    <td>Estado</td>
                    <td>Horario</td>
                    <td>Campos Referencia</td>
                    <td><%= t('all.edit') %></td>
                    <td><%= t('all.delete') %></td>
                  </tr>
                  <% @tx_filter.each do | fil | %>
                    <% @order+=1 %>
                    <%= render 'row', fil: fil %>
                  <% end %>
                <% end %>
              <% end %>
            </tbody>
          </table>
          <br>
          <% if @crearSession = 8 %>
          <%= link_to '<button class="btn btn-primary btn-xs" type="button" title="New Session"><i class="fa fa-user-circle-o"></i> '.html_safe + t('all.new') + '</button>'.html_safe, new_tx_sessions_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="traduciones" style="display: none;">
    <input id="traduSeleFormat" type="hidden" value="<%= t('views.tx_session_new.select_format') %>">
    <input id="traduSeleFeild" type="hidden" value="<%= t('views.tx_filter_detail_new.select_feild') %>">
    <input id="traduSeleList" type="hidden" value="<%= t('views.tx_filter_detail_new.select_list') %>">
    <input id="traduPlaceAddList" type="hidden" value="<%= t('views.tx_filter_detail_new.place_add_list') %>">
    <input id="deleteSession" type="hidden" value="<%= t('views.tx_session_index.btn_delete') %>">
    <input id="titleDelete" type="hidden" value="<%= t('swal.title_delete') %>">
    <input id="titleCancel" type="hidden" value="<%= t('swal.title_canceled') %>">
    <input id="txtAreSure" type="hidden" value="<%= t('swal.txt_are_sure') %>">
    <input id="txtCancel" type="hidden" value="<%= t('swal.txt_canceled') %>">
    <input id="btnConfirm" type="hidden" value="<%= t('swal.btn_confirm') %>">
    <input id="btnCancel" type="hidden" value="<%= t('swal.btn_cancel') %>">

    <input type="hidden" id="swalSorry" value="<%= t('swal.sorry') %>" >
    <input type="hidden" id="swalCondiIncompleta" value="<%= t('swal.txt_condi_incompleta') %>" >
    <input type="hidden" id="swalCondiExiste" value="<%= t('swal.txt_condi_existe') %>" >
    <input type="hidden" id="swalCondiDelete" value="<%= t('swal.txt_condi_delete') %>" >
    <input type="hidden" id="txtAnd" value="<%= t('views.tx_filter_detail_new.and') %>" >
    <input type="hidden" id="txtOr" value="<%= t('views.tx_filter_detail_new.or') %>" >
    <input type="hidden" id="swalDelete" value="<%= t('all.delete') %>" >
    <input type="hidden" id="dataWillLose" value="<%= t('swal.title_delete') %>" >
    <input type="hidden" id="youSure" value="<%= t('swal.txt_are_sure') %>" >
    <input type="hidden" id="btn_yes" value="<%= t('swal.btn_yes') %>" >
    <input type="hidden" id="btn_confir" value="<%= t('swal.btn_confirm') %>" >
    <input type="hidden" id="btn_cancel" value="<%= t('swal.btn_cancel') %>" >
    <input type="hidden" id="btn_cancel2" value="<%= t('swal.btn_cancel2') %>" >
    <input type="hidden" id="titleCancel" value="<%= t('swal.title_canceled') %>" >
    <input type="hidden" id="txtCancel" value="<%= t('swal.txt_canceled') %>" >
    <input type="hidden" id="noPalabra" value="<%= t('views.tx_filter_detail_new.notPalabra') %>" >
    <input type="hidden" id="noAddCone" value="<%= t('swal.txt_no_add_par_cone') %>" >
    <input type="hidden" id="noAddSinCon" value="<%= t('swal.txt_no_add_par_sinCon') %>" >
    <input type="hidden" id="session_active_title" value="<%= t('views.tx_session_index.session_active_title') %>">
    <input type="hidden" id="session_active_txt" value="<%= t('views.tx_session_index.session_active_txt') %>">
    <input type="hidden" id="name_filter_exists" value="<%= t('views.tx_session_index.name_filter_exists') %>">
    <input type="hidden" id="session_inactive" value="<%= t('views.tx_session_index.session_inactive') %>">
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $('.tree').treegrid();
    });

    $("[data-toggle=popover]").popover({html: true});

</script>

app/views/tx_sessions/new.html.erb
<%= render 'form', tx_session: @tx_session %>
<%#= link_to 'Back', tx_sessions_index_path %>

app/views/tx_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lay:</strong>
  <%= @tx_session.Lay_id %>
</p>

<p>
  <strong>Formato:</strong>
  <%= @tx_session.Format_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tx_session.Description %>
</p>

<p>
  <strong>Sessioncolor:</strong>
  <%= @tx_session.Sessioncolor %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @tx_session.Interval %>
</p>

<p>
  <strong>Inactive:</strong>
  <%= @tx_session.Inactive %>
</p>

<%= link_to 'Edit', edit_tx_sessions_path(@tx_session) %> |
<%= link_to 'Back', tx_sessions_index_path %>