config/routes.rb
Rails.application.routes.draw do
  resources :tx_schedule_references
  resources :tx_schedule_messages
  resources :tx_filter_schedules

  resources :tx_filters
  resources :tx_filter_details
  get 'transacction_type/dynamic', to: 'transacction_type#dynamic'
  resources :tconfigs
  get 'filtering_categorizations/dynamic', to: 'filtering_categorizations#dynamic'
  # get 'tx_sessions/index'

  get 'transacction_type/index', to: 'transacction_type#index'
  resources :transacction_type #'transacction_type/index', to: 'transacction_type#index'
  resources :tx_sessions
  resources :filtering_categorizations
  resources :states, :path => 'testadosxalerta'
  resources :states
  resources :testadosxalerta
  resources :table_orders
  get 'alert_release/index'
  post 'users/expire', to: 'users#expire'

  get 'users/expire', to: 'users#expire'

  get 'user_priority/index'
  get 'user_priority/assignPriority'
  get 'user_priority/assignPriorityPer'
  get 'user_priority/sessionsTran'
  get 'user_priority/groupsPer'

  get 'niv_alertamiento/index'
  get 'con_gen/index'


  filter :locale

  get 'alertc/par4'
  get 'alertc/par3'
  get 'alertc/par2'
  get 'alertc/par1'
  get 'alertn/histTran'
  get 'alertn/transacciones_alerta'
  get 'home/alertaBoton'
  get 'home/pie3'
  get 'home/pie2'
  get 'home/pie1' #, to: 'home#pie1'
  get 'home/contadorSuperior' #, to: 'home#pie1'
  get 'home/totalAlerts'
  get 'home/alertaTransaccional'
  get 'home/alertaPerfiles'
  get 'home/mensajeAlerta'
  get 'home/totalPoratender'
  get 'home/totalAtendidas'
  get 'home/settings_index'

  get 'chart/empty'
  get 'chart/pies'
  get 'chart/dynamic'

  resources 'chart'


  get 'alertn/alertTran', to: 'alertn#alertTran'
  get 'tbitacora/tbitacora'
  get 'tbitaobse/tbitaobse'
  get 'alertn/alertPer', to: 'alertn#alertPer'
  get 'alertc/busqueda', to: 'alertc#busqueda'

  resources :groups

  resources :views
  resources :profiles
  resources :permissions
  resources :areas
  resources :home
  resources :users
  resources :alertn
  resources :alertc
  resources :con_gen
  resources :chart, only: [:index, :dynamic]
  resources :home, only: [:index, :create]
  resources :mail_groups
  resources :gestor_settings


  # get '/:locale' => 'home#index'

  # devise_for :users
  devise_for :users, :controllers => {:registrations => "user/registrations", :sessions => "user/sessions"}, path: 'auth', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in'}
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root :to => 'home#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
      resources :expired_accounts
      get "expired_accounts/new"
    end
    get "auth/logout" => "devise/sessions#destroy"
  end
end

app/models/tx_filter_detail.rb
class TxFilterDetail < ApplicationRecord
  belongs_to :tx_filter
end

app/controllers/tx_filter_details_controller.rb
class TxFilterDetailsController < ApplicationController
  before_action :set_tx_filter_detail, only: [:show, :edit, :update, :destroy]

  # GET /tx_filter_details
  # GET /tx_filter_details.json
  def index
    @tx_filter_details = TxFilterDetail.all
  end

  # GET /tx_filter_details/1
  # GET /tx_filter_details/1.json
  def show
  end

  # GET /tx_filter_details/new
  def new
    @tx_filter_detail = TxFilterDetail.new

    ## Para pedir la ventana modal
    @tx_filter_schedule = TxFilterSchedule.new



    # Gon para traes los campos del formato y layout correspondiente
    @tx_sessions = TxSessions.all
    tx_sessions = TxSessions.all
    gon.sesiones = tx_sessions

    ## Gon para llenar selects Layout, Formato de ventana modal

    tCampos = Tcamposformato.all
    gon.tCamposFormatos = tCampos

    tLays = Tcamposlay.all
    gon.tCamposLays = tLays


    ## Campos de Referencia
    camposRefCheck = TxScheduleReference.all
    gon.camposRef = camposRefCheck

    filtros = TxFilter.all
    gon.allFiltros = filtros

    gon.false = true


    @@filter_id = params[:id]
    if params[:id].present?
      @id = params[:id]
      @tx_filter = TxFilter.where(:Id => @id)
      @tx_filter_schedule = TxFilterSchedule.where(:filter_id => @id)


    end
  end

  # GET /tx_filter_details/1/edit
  def edit

    # Gon para traes los campos del formato y layout correspondiente
    @tx_sessions = TxSessions.all
    tx_sessions = TxSessions.all
    gon.sesiones = tx_sessions

    ## Gon para llenar selects Layout, Formato de ventana modal

    tCampos = Tcamposformato.all
    gon.tCamposFormatos = tCampos

    tLays = Tcamposlay.all
    gon.tCamposLays = tLays
    gon.false = true
  end

  # POST /tx_filter_details
  # POST /tx_filter_details.json
  def create



    if ( params[:_method].present? && params[:_method] == 'create' )
      @tx_filter_detail = TxFilterDetail.new


    else
      respond_to do |format|


        ### Actualizar, reordenar, agrega y elimina "TODAS LAS condiciones del filtro".
        if params[:update_filter_detail] == '0'
          if !params[:update_filter_detail].nil?
            if ( params[:SoyNuevo] == 'true' && params[:ListarCondiciones] == 'true' )

              ## En esta variable obtengo todos los datos de las condiciones que vienen de un input en la vista new con id="filtroNew"
              @filtroCondiciones = params[:filtroUp].split(',')

              ## Esta variable guarda el total de condiciones que hay existentes en base y el valor es asignado por un script document.ready cuando se ejecuta la vista
              @total_condi_input = params[:total_condi_input]

              @cont = 0 # Contador para ir alamacenando los valores en diferentes variables
              @numC = 0 # Variable que es asiganada como numero de condición
              @updateCondiciones = false # Boleano para ejecutar un if que puede actualizar o crear condiciones


              ## Estas variables guardan los valores de cada condición
              @numberConUp
              @conectorUp
              @negadoUp
              @operadorUp
              @parentesisUp
              @valorUp
              @campoFormatoIdUp
              @posisionUp
              @lengthUp

              ## Itero los valores del arreglo "Condiciones", y voy guardando valor por valor en las variables antes creadas
              @filtroCondiciones.each do | datos |
                @cont += 1 ## Incremento el contador para guardar los valaores

                if( @cont == 1 )
                  @numberConUp = datos
                elsif ( @cont == 2)
                  @conectorUp = datos
                elsif ( @cont == 3 )
                  @negadoUp = datos
                elsif ( @cont == 4 )
                  @operadorUp =datos
                elsif ( @cont == 5 )
                  @parentesisUp = datos
                elsif ( @cont == 6 )
                  @valorUp = datos
                elsif ( @cont == 7 )
                  @campoFormatoIdUp = datos
                elsif ( @cont == 8 )
                  @posisionUp = datos
                elsif ( @cont == 9 )
                  @lengthUp = datos
                  @cont = 0 ######### Contador comienza desde cero
                  @updateCondiciones = true ####### Boleano que permite ejecutar el if para actualizar o crear las "Condiciones"
                end

                if @updateCondiciones
                  @updateCondiciones = false
                  @numC += 1 ### Esta variable reprenta el valor para el campo conditionnumber

                  ## Si esta existe esta condiciones con este id de filtro y número de condición se ejecuta el sig. if
                  @condicionesFiltro = TxFilterDetail.where(:filter_id => @@filter_id).where(:conditionnumber => @numC).present?

                  if @condicionesFiltro

                    ## Hago una consulta especifica solo a ese id de filtro y numero especifico de condicion para actualizar los datos
                    @upCons = TxFilterDetail.where(:filter_id => @@filter_id).where(:conditionnumber => @numC)
                    @upCons.each do |cd|
                      cd.conditionnumber = @numC
                      cd.connector = @conectorUp
                      cd.denied = @negadoUp
                      cd.operator = @operadorUp
                      cd.parenthesis = @parentesisUp
                      cd.value = @valorUp
                      cd.fieldFormat_id = @campoFormatoIdUp
                      cd.position = @posisionUp
                      cd.lenght = @lengthUp
                      cd.save
                    end

                  else

                    ## Si no se encontro ninguna condición con el número id de filtro y  número de condición se crea un nuevo elemento en la tabla "Condición"
                    @tx_filter_detail = TxFilterDetail.new
                    @tx_filter_detail.filter_id = @@filter_id
                    @tx_filter_detail.conditionnumber = @numC
                    @tx_filter_detail.connector = @conectorUp
                    @tx_filter_detail.denied = @negadoUp
                    @tx_filter_detail.operator = @operadorUp
                    @tx_filter_detail.parenthesis = @parentesisUp
                    @tx_filter_detail.value = @valorUp
                    @tx_filter_detail.fieldFormat_id = @campoFormatoIdUp
                    @tx_filter_detail.position = @posisionUp
                    @tx_filter_detail.lenght = @lengthUp
                    @tx_filter_detail.save
                  end
                end
              end
              ##### Finaliza la iteración de los valores de las condiciones.

              @nu = @numC.to_i ## Este es el valor de la ultima condición
              @to = @total_condi_input.to_i # Número de condiciones que existian al entrar a la vista new


               ## Las condiciones solo son eliminadas en vista - es decir hasta este punto todavia existen todas las condiciones en base y ninguna a sido eliminada todavia
              #  Al menos que el número de condicion sea menor al total de condiciones se ejecuta el sig. if para hacer un consulta y eliminar las ultimas condiciones ya que estas
              #  se repetian " a  consecuancia de iterar los valores del arreglo @filtroCondiciones"
              if @to > @nu
                @res = @to - @nu
                puts "##################################################### #{@res}"

                @desCondi = TxFilterDetail.where(:filter_id => @@filter_id).last(@res)
                @desCondi.each do |desCondi|
                  desCondi.destroy
                end
              end

            end
          end
        end

        ## Actualiza los datos del filtro, Descripción (Description), tipo de filtro (Order_number), color del filtro (Backgroundcolor).
        if params[:update_filter] == '0'
          if !params[:update_filter].nil?
            if ( params[:SoyNuevo] == 'true' )
              cero = false
              @tx_filter = TxFilter.where(:Id => @@filter_id)
            else
              @tx_filter_detail = TxFilterDetail.find(params[:id])
              cero = false
              @tx_filter = TxFilter.where(:Id => @tx_filter_detail.Session_id)
            end
            @description = params[:desFiltro]
            @typeFilter = params[:type_filter]
            @color = params[:Backgroundcolor]

            @tx_filter.each do | filtro|
              filtro.Description = params[:desFiltro]
              filtro.Order_number = params[:type_filter]

              if @typeFilter != '0'
                filtro.Backgroundcolor = @color
              else
                filtro.Backgroundcolor = nil
              end
              filtro.save
            end
          end
        end

        ## Actualizar los campos de referencia del filtro
        if params[:update_camposRef] == "0"
          if !params[:update_camposRef].nil?
            @cmpRef = params[:arrCmpRe]

            ## Si existen elementos en el arreglo se borraran esos registros "id" que van en el array
            if @cmpRef.present?
              @arrCmpRef = @cmpRef.split(',')
              @arrCmpRef.each do | idCmpRefTable |
                @tx_schedule_reference = TxScheduleReference.find(idCmpRefTable)
                @tx_schedule_reference.destroy
              end
            end

            @camposRefUpdate = params[:tx_shcedule_reference]

            if @camposRefUpdate.present?
              @camposRefUpdate.each do |key, obj|
                @key = key
                @idCmpRefTab = obj[:id]

                if @idCmpRefTab.present?
                  @tx_schedule_reference = TxScheduleReference.find(@idCmpRefTab)
                  @tx_schedule_reference.update(obj.permit(:id, :field_formatId))
                else
                  @tx_schedule_reference = TxScheduleReference.new(obj.permit(:field_formatId))
                  @tx_schedule_reference.Filter_id = @@filter_id

app/helpers/tx_filter_details_helper.rb
module TxFilterDetailsHelper
end

app/views/tx_filter_details/_form.html.erb
<%= stylesheet_link_tag 'tx_filter_details' %>
<div class="ibox-content" style="padding: 4em 1.5em">
  <%= form_for (tx_filter_detail) do |f| %>
    <% if tx_filter_detail.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tx_filter_detail.errors.count, "error") %> prohibited this tx_filter_detail from being saved:</h2>

        <ul>
          <% tx_filter_detail.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <article class="row">
      <% disabled = ''%>
      <% if tx_filter_detail.parenthesis != '0' %>
        <% disabled = 'disabled'%>
      <% end %>
      <%= f.hidden_field :parenthesis %>

      <div class="col-lg-1 cont-denied">
        <%= f.label :denied, t('views.tx_filter_detail_new.denied'), style:'display: block' %>
        <%= f.check_box :denied %>
      </div>
      <div class="col-lg-1 cont-connector">
        <!-- Inputs AND y OR -->
        <input type="hidden" id="or" value="<%= t('views.tx_filter_detail_new.or') %>">
        <input type="hidden" id="and" value="<%= t('views.tx_filter_detail_new.and') %>">

        <%= f.label :connector, t('views.tx_filter_detail_new.connectors'), style:'display: block' %>
        <input type="hidden" id="connector" name="tipoConector" value="<%= tx_filter_detail.connector %>">
        <% if tx_filter_detail.connector. != '-1'  %>
        <span class="btn btn-primary btn-xs conectorEdit" title="Cambiar conector">
          <% if tx_filter_detail.connector == "0" %>
            <%= t('views.tx_filter_detail_new.or') %>
          <% elsif tx_filter_detail.connector == "1" %>
            <%= t('views.tx_filter_detail_new.and') %>
          <% end %>
        </span>
        <% end %>
      </div>
      <div class="col-lg-2 cont-campo">

        <% @idFilter = tx_filter_detail.filter_id %>
        <% @idSession = TxFilter.where(:Id => @idFilter) %>

        <% @idSession.each do | filter | %>
          <input type="hidden" id="idSession" value="<%= filter.Session_id%>">
        <% end %>

        <!-- Valor del campo -->
        <input type="hidden" id="campoId" value="<%= tx_filter_detail.fieldFormat_id %>">
        <!-- Valor de su posision -->
        <%= f.text_field :position, id:'posEdit', type:'hidden' %>
        <!-- Valor de su longitud -->
        <%= f.text_field :lenght, id:'lengEdit', type:'hidden' %>
        <%= f.label :fieldFormat_id, t('views.tx_filter_detail_new.feild') %>
        <select name="campo" id="selectCampo" class="form-control" <%= disabled %>></select>
      </div>
      <div class="col-lg-2 cont-operator">
        <input type="hidden" id="operatorVal" value="<%= tx_filter_detail.operator %>" >
        <%= f.label :operator, t('views.tx_filter_detail_new.operators') %>
        <select name="operator" id="selectOperator" class="form-control" <%= disabled %>>
          <option value="0"> = </option>
          <option value="1"> <> </option>
          <option value="2"> > </option>
          <option value="3"> >= </option>
          <option value="4"> < </option>
          <option value="5"> <= </option>
          <option value="6"> Like </option>
          <option value="7"> In </option>
          <option value="8"> Between </option>
        </select>
      </div>
      <div class="col-lg-3 cont-values">
        <%= f.label :value, t('views.tx_filter_detail_new.value') +' '+ '('+ t('views.tx_filter_detail_new.ees') +')' %>
        <% if tx_filter_detail.operator == '8' %>
          <% @values = tx_filter_detail.value.split('}').join(" ")%>
          <% @valoresBetween = @values.split('{') %>
          <% @value = @valoresBetween[1].delete(' ') %>
          <% @valorDos = @valoresBetween[2] %>
          <%# dis = "block" %>
        <% else %>
          <% @value = tx_filter_detail.value %>
          <% dis = "none" %>
        <% end %>
        <div class="cont-inputs">
          <div class="values valUno">
            <input type="text" id="valorUno" name="valor" value="<%= @value %>" class="form-control" <%= disabled %> autocomplete="off">
          </div>
          <div class="values valDos" style="display: <%= dis %>">
            <input type="text" id="valorDos" name="valorDos" value="<%= @valorDos %>" class="form-control" <%= disabled %> autocomplete="off">
          </div>
        </div>
      </div>
    </article>

    <div class="action" style="margin-top: 5em">
      <%= button_tag(type: 'submit', class: 'btn btn-primary btn-xs') do %>
        <%= t('views.mail_group_form.btn_Save') %>
      <% end %>

      <a href="/tx_filter_details/new?id=<%= tx_filter_detail.filter_id %>" class="btn btn-primary btn-xs"><%= t('all.back') %></a>
    </div>
  <% end %>

  <div class="traducciones" style="display: none;">
    <input id="traduSeleFormat" type="hidden" value="<%= t('views.tx_session_new.select_format') %>">
    <input id="traduSeleFeild" type="hidden" value="<%= t('views.tx_filter_detail_new.select_feild') %>">
    <input id="traduSeleList" type="hidden" value="<%= t('views.tx_filter_detail_new.select_list') %>">
    <input id="traduPlaceAddList" type="hidden" value="<%= t('views.tx_filter_detail_new.place_add_list') %>">
    <input type="hidden" id="swalSorry" value="<%= t('swal.sorry') %>" >
    <input type="hidden" id="swalCondiIncompleta" value="<%= t('swal.txt_condi_incompleta') %>" >
    <input type="hidden" id="swalCondiExiste" value="<%= t('swal.txt_condi_existe') %>" >
    <input type="hidden" id="swalCondiDelete" value="<%= t('swal.txt_condi_delete') %>" >
    <input type="hidden" id="txtAnd" value="<%= t('views.tx_filter_detail_new.and') %>" >
    <input type="hidden" id="txtOr" value="<%= t('views.tx_filter_detail_new.or') %>" >
    <input type="hidden" id="swalDelete" value="<%= t('all.delete') %>" >
    <input type="hidden" id="dataWillLose" value="<%= t('swal.title_delete') %>" >
    <input type="hidden" id="youSure" value="<%= t('swal.txt_are_sure') %>" >
    <input type="hidden" id="btn_yes" value="<%= t('swal.btn_yes') %>" >
    <input type="hidden" id="btn_confir" value="<%= t('swal.btn_confirm') %>" >
    <input type="hidden" id="btn_cancel" value="<%= t('swal.btn_cancel') %>" >
    <input type="hidden" id="btn_cancel2" value="<%= t('swal.btn_cancel2') %>" >
    <input type="hidden" id="titleCancel" value="<%= t('swal.title_canceled') %>" >
    <input type="hidden" id="txtCancel" value="<%= t('swal.txt_canceled') %>" >
    <input type="hidden" id="noPalabra" value="<%= t('views.tx_filter_detail_new.notPalabra') %>" >
    <input type="hidden" id="noAddCone" value="<%= t('swal.txt_no_add_par_cone') %>" >
    <input type="hidden" id="noAddSinCon" value="<%= t('swal.txt_no_add_par_sinCon') %>" >
  </div>
</div>

app/views/tx_filter_details/_row.html.erb
<tr id="<%= horario.id %>">
  <td><%= horario.Hr_Start %></td>
  <td><%= horario.Hr_End %></td>
  <td> <%= link_to '<i class="fa fa-pencil"></i>'.html_safe , edit_tx_filter_schedule_path(horario), remote: true, class:'btn btn-warning btn-xs' %> </td>
  <td> <%= link_to '<i class="fa fa-trash"></i>'.html_safe, horario, method: :delete, class:'btn btn-danger btn-xs' %> </td>
</tr>

app/views/tx_filter_details/edit.html.erb
<div class="row">
  <section class="col-lg-12">
    <div class="ibox-title">
      <h1><%= t('all.edit') %> <%= t('views.tx_filter_index.condition') %></h1>
    </div>
    <%= render 'form', tx_filter_detail: @tx_filter_detail %>
<!--    <%#= link_to 'Show', @tx_filter_detail %> |-->
    <%#= link_to 'Back', tx_filter_details_path %>
  </section>
</div>

app/views/tx_filter_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tx Filter Details</h1>

<table>
  <thead>
    <tr>
      <th>Conditionnumber</th>
      <th>Connector</th>
      <th>Length</th>
      <th>Denied</th>
      <th>Operator</th>
      <th>Parenthesis</th>
      <th>Position</th>
      <th>Value</th>
      <th>Fieldlay</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tx_filter_details.each do |tx_filter_detail| %>
      <tr>
        <td><%= tx_filter_detail.conditionnumber %></td>
        <td><%= tx_filter_detail.connector %></td>
        <td><%= tx_filter_detail.denied %></td>
        <td><%= tx_filter_detail.operator %></td>
        <td><%= tx_filter_detail.parenthesis %></td>
        <td><%= tx_filter_detail.value %></td>
        <td><%= tx_filter_detail.fieldFormat_id %></td>
        <td><%= tx_filter_detail.position %></td>
        <td><%= tx_filter_detail.lenght %></td>
        <td><%= link_to 'Show', tx_filter_detail %></td>
        <td><%= link_to 'Edit', edit_tx_filter_detail_path(tx_filter_detail) %></td>
        <td><%= link_to 'Destroy', tx_filter_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tx Filter Detail', new_tx_filter_detail_path %>

app/views/tx_filter_details/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tx_filter_detail_path(@tx_filter_detail) %> |
<%= link_to 'Back', tx_filter_details_path %>